clear; clc;

matlabDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(matlabDir);
outDir = fullfile(repoRoot,'rtl','tx');
beta = 0.35;
spanSymbols = 10;
sps = 48;
scale = 2^16;

h = localRRC(beta,spanSymbols,sps);
hq = round(h*scale);

txtPath = fullfile(outDir,'tx_rrc_coeffs_q16.txt');
fid=fopen(txtPath,'w'); assert(fid>=0); cleaner=onCleanup(@() fclose(fid));
for k=1:numel(hq), fprintf(fid,'%d\n',hq(k)); end
clear cleaner

vhPath = fullfile(outDir,'tx_rrc_coeffs_case.vh');
fid=fopen(vhPath,'w'); assert(fid>=0); cleaner=onCleanup(@() fclose(fid));
fprintf(fid,'// Generated by design_tx_rrc.m: beta=%.2f, span=%d, sps=%d, scale=%d\n', ...
    beta,spanSymbols,sps,scale);
for k=1:numel(hq)
    if hq(k)<0
        fprintf(fid,"            %d: tx_rrc_coeff = -18'sd%d;\n",k-1,abs(hq(k)));
    else
        fprintf(fid,"            %d: tx_rrc_coeff = 18'sd%d;\n",k-1,hq(k));
    end
end
clear cleaner

[H,F]=freqz(double(hq)/scale,1,262144,245.76e6);
fprintf('TX_RRC_TAPS=%d\n',numel(hq));
fprintf('TX_RRC_SPS=%d\n',sps);
fprintf('TX_RRC_BETA=%.8g\n',beta);
fprintf('TX_RRC_CENTER_CODE=%d\n',hq((numel(hq)+1)/2));
fprintf('TX_RRC_MAX_POLYPHASE_ABS_SUM=%d\n',max(arrayfun(@(p) sum(abs(hq(p:sps:end))),1:sps)));
fprintf('TX_RRC_DC_GAIN=%.12g\n',abs(H(1)));
fprintf('TX_RRC_EDGE_GAIN_DB=%.6f\n',20*log10(abs(H(find(F>=2.56e6,1)))/abs(H(1))));

function h = localRRC(beta,span,sps)
t=(-span*sps/2:span*sps/2).'/sps;
h=zeros(size(t));
for k=1:numel(t)
    x=t(k);
    if abs(x)<1e-12
        h(k)=1+beta*(4/pi-1);
    elseif abs(abs(x)-1/(4*beta))<1e-12
        h(k)=beta/sqrt(2)*((1+2/pi)*sin(pi/(4*beta))+(1-2/pi)*cos(pi/(4*beta)));
    else
        h(k)=(sin(pi*x*(1-beta))+4*beta*x*cos(pi*x*(1+beta)))/(pi*x*(1-(4*beta*x)^2));
    end
end
h=h/sqrt(sum(h.^2));
end
